addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - libcups2-dev # for aeroo

language: python
sudo: false
cache: pip

python:
  - "2.7"

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='jjscarafia'
  - TRANSIFEX_ORGANIZATION='adhoc'
  # to get secure, run 'travis encrypt TRANSIFEX_PASSWORD=[transifex_password] -r [github_repo]'
  # example of github repo 'ingadhoc/odoo-infrastructure'
  - secure: dzgJixNgHTzZrEYfXxesEJ1ql6l/jSm5zS4WXTEhQT9eVv8gDEWv157wUZKEONUA6yTu7CatWKMFbVOQE6+hSTYZUM4zXE6276fITq0rekRKnukQJu8VbNt+tUP/MXJ5qEvmDJcf7+1rRmOYp2hPrDzCQ7ciu77ZUV1CKjrSFcTZn8LuI5TuAozZdTVXdhsoj2kuSqixL4NIBNx3NnfQV7HFugHA878Grm9SXUjIBKiG+WNCUicoHK09dk6rYTSiSjVo1UpJYaxbVMjiy9D0H33gEvSiRpq8eDpXFkHBLztkpqH+j4L0B7bkqyhEwF5Uh0sB+5lU3oNmeHo8a6U9ck5FGddlNB5u9Gm5hVLYc5zjiKUVBrHkdftUlOudiNE0CRwKa+/Lft5+CIy4vlP+aJ3p2NqYVOW9/Cf8PzzENsOtfLZTG5QEM/YRS3vuE9MxqwqTOM7pGgJN39Z8lkPwwKMBgCcY211sxBtHs3pysOk2CVFU8gW2C1eTmdUWr74RSKwtjGDk0mIk0Ff4Z0m1/U/LiOHYWuRNImUlAhB2l0EVOtHb2bOZaYXCviwZGeIk5+dkqoo2Q7OPnMIZPQ+O8RAUTKMhYqfBpLIUZRL4q3Tozi0p3rsyKa1mxuum6PC/Y0ByyY9yHRvykdjZOeneJUnbCWjRUStq0/tIHrkDEys=

  matrix:
  # TODO enable lint check
  #- LINT_CHECK="1"
  - TRANSIFEX="1"
  # TODO enable this modules I have to exclude because i can not find the error
  - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="nautical_translations,nautical_search_by_ni"
  - UNIT_TEST="1" ODOO_REPO="odoo/odoo" EXCLUDE="nautical_translations,nautical_search_by_ni"

virtualenv:
  system_site_packages: true

install:
  # aeroo reports
  - git clone https://github.com/aeroo/aeroo_reports.git ${HOME}/aeroo_reports
  - pip install git+https://github.com/aeroo/aeroolib.git@master pycups==1.9.68

  # odoo addons adhoc
  - git clone https://github.com/ingadhoc/odoo-addons.git -b 8.0 ${HOME}/odoo-addons

  # odoo argentina
  # TODO change to 8.0 when ready
  - git clone https://github.com/ingadhoc/odoo-argentina.git -b 8.0 ${HOME}/odoo-argentina
  - pip install geopy==0.95.1 BeautifulSoup 

  # oca server tools
  - git clone https://github.com/OCA/server-tools.git ${HOME}/server-tools

  # repository requirements
  - pip install -r requirements.txt

  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  coveralls
